<?php
require("../../inc/header.php");

/*
		SoftName : EmpireBak Version 2010
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

DoSetDbChar('utf8');
E_D("DROP TABLE IF EXISTS `v9_category`;");
E_C("CREATE TABLE `v9_category` (
  `catid` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `siteid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `module` varchar(15) NOT NULL,
  `type` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `modelid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `parentid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `arrparentid` varchar(255) NOT NULL,
  `child` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `arrchildid` mediumtext NOT NULL,
  `catname` varchar(30) NOT NULL,
  `style` varchar(5) NOT NULL,
  `image` varchar(100) NOT NULL,
  `description` mediumtext NOT NULL,
  `parentdir` varchar(100) NOT NULL,
  `catdir` varchar(30) NOT NULL,
  `url` varchar(100) NOT NULL,
  `items` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `hits` int(10) unsigned NOT NULL DEFAULT '0',
  `setting` mediumtext NOT NULL,
  `listorder` smallint(5) unsigned NOT NULL DEFAULT '0',
  `ismenu` tinyint(1) unsigned NOT NULL DEFAULT '1',
  `sethtml` tinyint(1) unsigned NOT NULL DEFAULT '0',
  `letter` varchar(30) NOT NULL,
  `usable_type` varchar(255) NOT NULL,
  PRIMARY KEY (`catid`),
  KEY `module` (`module`,`parentid`,`listorder`,`catid`),
  KEY `siteid` (`siteid`,`type`)
) ENGINE=MyISAM AUTO_INCREMENT=29 DEFAULT CHARSET=utf8");
E_D("replace into `v9_category` values('1','1','content','1','0','0','0','1','1,4','网站介绍','','','','','siteinfo','/html/siteinfo/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''1'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','50','0','0','wangzhanjieshao','');");
E_D("replace into `v9_category` values('2','1','content','1','0','0','0','0','2','关于我们','','','','','about','/html/about/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''8kna'',\n  ''page_template'' => ''page_about'',\n  ''meta_title'' => ''关于我们'',\n  ''meta_keywords'' => ''关于我们'',\n  ''meta_description'' => ''关于我们'',\n  ''category_ruleid'' => ''33'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','7','1','0','guanyuwomen','');");
E_D("replace into `v9_category` values('3','1','content','1','0','0','0','0','3','联系我们','','','','','contact','/html/contact/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''8kna'',\n  ''page_template'' => ''page_contact'',\n  ''meta_title'' => ''联系方式'',\n  ''meta_keywords'' => ''联系方式'',\n  ''meta_description'' => ''联系方式'',\n  ''category_ruleid'' => ''33'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','8','1','0','lianxiwomen','');");
E_D("replace into `v9_category` values('4','1','content','1','0','1','0,1','0','4','版权声明','','','','siteinfo/','copyright','http://localhost.8kna.com/index.php?m=content&c=index&a=lists&catid=4','0','0','array (\n  ''ishtml'' => ''0'',\n  ''template_list'' => ''default'',\n  ''page_template'' => ''page'',\n  ''meta_title'' => ''版权声明'',\n  ''meta_keywords'' => ''版权声明'',\n  ''meta_description'' => ''版权声明'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','4','1','0','banquanshengming','');");
E_D("replace into `v9_category` values('5','1','content','1','0','0','0','0','5','在线订单','','','','','order','/html/order/','0','0','array (\n  ''ishtml'' => ''1'',\n  ''template_list'' => ''8kna'',\n  ''page_template'' => ''page_order'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''category_ruleid'' => ''33'',\n  ''show_ruleid'' => '''',\n  ''repeatchargedays'' => ''1'',\n)','9','1','0','zaixiandingdan','');");
E_D("replace into `v9_category` values('6','1','content','0','1','0','0','1','6,14,15,16,17,18','新闻中心','','','','','news','/html/news/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','3','1','0','xinwenzhongxin','');");
E_D("replace into `v9_category` values('7','1','content','0','2','0','0','0','7','下载','','','','','down','http://localhost.8kna.com/index.php?m=content&c=index&a=lists&catid=7','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''default'',\n  ''category_template'' => ''category_download'',\n  ''list_template'' => ''list_download'',\n  ''show_template'' => ''show_download'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''6'',\n  ''show_ruleid'' => ''16'',\n)','50','0','0','xiazai','');");
E_D("replace into `v9_category` values('8','1','content','0','3','0','0','1','8,13,12,11,10,9','作品展示','','','','','works','/html/works/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','1','1','0','zuopinzhanshi','');");
E_D("replace into `v9_category` values('9','1','content','0','3','8','0,8','0','9','最新作品','','','','works/','latest','/html/latest/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','5','1','0','zuixinzuopin','');");
E_D("replace into `v9_category` values('10','1','content','0','3','8','0,8','0','10','婚纱摄影','','','','works/','wedding','/html/wedding/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','4','1','0','hunshasheying','');");
E_D("replace into `v9_category` values('11','1','content','0','3','8','0,8','0','11','时尚写真','','','','works/','fashion','/html/fashion/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','3','1','0','shishangxiezhen','');");
E_D("replace into `v9_category` values('12','1','content','0','3','8','0,8','0','12','商业摄影','','','','works/','commercial','/html/commercial/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','2','1','0','shangyesheying','');");
E_D("replace into `v9_category` values('13','1','content','0','3','8','0,8','0','13','首页上方展示区','','','','works/','homeshow','/html/homeshow/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category_picture'',\n  ''list_template'' => ''list_picture'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','1','1','0','shouyeshangfangzhanshiqu','');");
E_D("replace into `v9_category` values('14','1','content','0','1','6','0,6','0','14','新闻活动','','','','news/','xwhd','/html/xwhd/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','1','1','0','xinwenhuodong','');");
E_D("replace into `v9_category` values('15','1','content','0','1','6','0,6','0','15','结婚课堂','','','','news/','jhkt','/html/jhkt/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','2','1','0','jiehunketang','');");
E_D("replace into `v9_category` values('16','1','content','0','1','6','0,6','0','16','新人课堂','','','','news/','xrkt','/html/xrkt/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','3','1','0','xinrenketang','');");
E_D("replace into `v9_category` values('17','1','content','0','1','6','0,6','0','17','论坛热帖','','','','news/','ltrt','/html/ltrt/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','4','1','0','luntanretie','');");
E_D("replace into `v9_category` values('18','1','content','0','1','6','0,6','0','18','服务小贴士','','','','news/','fwxts','/html/fwxts/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','5','1','0','fuwuxiaotieshi','');");
E_D("replace into `v9_category` values('19','1','content','0','1','0','0','1','19,20,21,22','服务报价','','','','','services','/html/services/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_service'',\n  ''show_template'' => ''show_service'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','4','1','0','fuwubaojia','');");
E_D("replace into `v9_category` values('20','1','content','0','1','19','0,19','0','20','婚纱套系','','','','services/','hstx','/html/hstx/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','1','1','0','hunshataoxi','');");
E_D("replace into `v9_category` values('21','1','content','0','1','19','0,19','0','21','写真套系','','','','services/','xztx','/html/xztx/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','2','1','0','xiezhentaoxi','');");
E_D("replace into `v9_category` values('22','1','content','0','1','19','0,19','0','22','商业套系','','','','services/','sytx','/html/sytx/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list'',\n  ''show_template'' => ''show'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','3','1','0','shangyetaoxi','');");
E_D("replace into `v9_category` values('23','1','content','0','3','0','0','0','23','客片欣赏','','','','','guest','http://localhost.8kna.com/{\$categorydir}{\$catdir}/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''0'',\n  ''content_ishtml'' => ''0'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_case'',\n  ''show_template'' => ''show_picture'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''1'',\n  ''show_ruleid'' => ''11'',\n)','2','1','0','kepianxinshang','');");
E_D("replace into `v9_category` values('24','1','content','0','1','0','0','1','24,25,26,27','外景展示','','','','','exterior','/html/exterior/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_location'',\n  ''show_template'' => ''show_location'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','5','1','0','waijingzhanshi','');");
E_D("replace into `v9_category` values('25','1','content','0','1','24','0,24','0','25','市内景区','','','','exterior/','snjq','/html/snjq/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_location'',\n  ''show_template'' => ''show_location'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','1','1','0','shineijingqu','');");
E_D("replace into `v9_category` values('26','1','content','0','1','24','0,24','0','26','远郊景区','','','','exterior/','yjjq','/html/yjjq/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_location'',\n  ''show_template'' => ''show_location'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','2','1','0','yuanjiaojingqu','');");
E_D("replace into `v9_category` values('27','1','content','0','1','24','0,24','0','27','近邻景区','','','','exterior/','jljq','/html/jljq/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_location'',\n  ''show_template'' => ''show_location'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','3','1','0','jinlinjingqu','');");
E_D("replace into `v9_category` values('28','1','content','0','1','0','0','0','28','爱情微电影','','','','','movie','/html/movie/','0','0','array (\n  ''workflowid'' => '''',\n  ''ishtml'' => ''1'',\n  ''content_ishtml'' => ''1'',\n  ''create_to_html_root'' => ''0'',\n  ''template_list'' => ''8kna'',\n  ''category_template'' => ''category'',\n  ''list_template'' => ''list_dress'',\n  ''show_template'' => ''show_dress'',\n  ''meta_title'' => '''',\n  ''meta_keywords'' => '''',\n  ''meta_description'' => '''',\n  ''presentpoint'' => ''1'',\n  ''defaultchargepoint'' => ''0'',\n  ''paytype'' => ''0'',\n  ''repeatchargedays'' => ''1'',\n  ''category_ruleid'' => ''32'',\n  ''show_ruleid'' => ''31'',\n)','6','1','0','aiqingweidianying','');");

require("../../inc/footer.php");
?>